### S04E05 - AI Devs - Food Warehouse
POST {{ai_devs_hub_url}}/verify
Content-Type: application/json

{
  "apikey": "{{ai_devs_api_key}}",
  "task": "foodwarehouse",
  "answer": {
    "tool": "help"
  }
}
