### S02E05 - AI Devs - Drone
POST {{ai_devs_hub_url}}/verify
Content-Type: application/json

{
  "apikey": "{{ai_devs_api_key}}",
  "task": "drone",
  "answer": {
    "instructions": [
      "test"
    ]
  }
}
